[cluster]
node_id = 2
listen_address = "127.0.0.1:9082"
initial_cluster = [
    { id = 1, name = "n1", ip = "127.0.0.1", port = 9081, role = 1 },
    { id = 2, name = "n2", ip = "127.0.0.1", port = 9082, role = 1 },
    { id = 3, name = "n3", ip = "127.0.0.1", port = 9083, role = 1 },
]
db_root_dir = "./db"
log_dir = "./logs"

[raft.commit_handler]
batch_size = 5000

[raft.replication]
rpc_append_entries_in_batch_threshold = 5000
