[cluster]
node_id = 2
listen_address = "127.0.0.1:9082"
initial_cluster = [
    { id = 1, address = "127.0.0.1:9081", role = 1, status = 2 },
    { id = 2, address = "127.0.0.1:9082", role = 1, status = 2 },
    { id = 3, address = "127.0.0.1:9083", role = 1, status = 2 },
]
db_root_dir = "./db"
log_dir = "./logs"

[raft]
general_raft_timeout_duration_in_ms = 100

[raft.commit_handler]
batch_size = 5000

[raft.replication]
rpc_append_entries_in_batch_threshold = 5000
