[cluster]
node_id = 2
listen_address = "127.0.0.1:9082"
initial_cluster = [
    { id = 1, name = "n1", address = "127.0.0.1:9081", role = 1, status = 0 },
    { id = 2, name = "n2", address = "127.0.0.1:9082", role = 1, status = 0 },
    { id = 3, name = "n3", address = "127.0.0.1:9083", role = 1, status = 0 },
]
db_root_dir = "./db"
log_dir = "./logs"

[raft.commit_handler]
batch_size = 5000

[raft.replication]
rpc_append_entries_in_batch_threshold = 5000
