[cluster]
node_id = 3
listen_address = "127.0.0.1:9083"
initial_cluster = [
    { id = 1, address = "127.0.0.1:9081", role = 1, status = 2 },
    { id = 2, address = "127.0.0.1:9082", role = 1, status = 2 },
    { id = 3, address = "127.0.0.1:9083", role = 1, status = 2 },
]
db_root_dir = "./db"
log_dir = "./logs"

[monitoring]
prometheus_enabled = true
prometheus_port = 8083

[raft]
general_raft_timeout_duration_in_ms = 100


[raft.commit_handler]
batch_size = 5000

[raft.replication]
rpc_append_entries_in_batch_threshold = 5000

[raft.snapshot]
enable = false
