[cluster]
node_id = 5
listen_address = "127.0.0.1:9085"
initial_cluster = [
    { id = 1, address = "127.0.0.1:9081", role = 1, status = 2 },
    { id = 2, address = "127.0.0.1:9082", role = 1, status = 2 },
    { id = 3, address = "127.0.0.1:9083", role = 1, status = 2 },
    { id = 4, address = "127.0.0.1:9084", role = 3, status = 0 },
    { id = 5, address = "127.0.0.1:9085", role = 3, status = 0 },
]
db_root_dir = "./db"
log_dir = "./logs"

[monitoring]
prometheus_enabled = true
prometheus_port = 8085

[raft]
general_raft_timeout_duration_in_ms = 100

[retry.join_cluster]
max_retries = 3      # Maximum number of retries (recommended: 3)
timeout_ms = 500     # Single request timeout (recommended: 500-1000ms)
base_delay_ms = 3000 # Initial backoff delay (recommended: 3000ms)
max_delay_ms = 60000 # Maximum backoff delay (recommended: <=1m)

[raft.snapshot]
enable = false
