[cluster]
node_id = 5
listen_address = "127.0.0.1:9085"
initial_cluster = [
    { id = 1, address = "127.0.0.1:9081", role = 1, status = 2 },
    { id = 2, address = "127.0.0.1:9082", role = 1, status = 2 },
    { id = 3, address = "127.0.0.1:9083", role = 1, status = 2 },
    { id = 4, address = "127.0.0.1:9084", role = 3, status = 0 },
    { id = 5, address = "127.0.0.1:9085", role = 3, status = 0 },
]
db_root_dir = "./db"
log_dir = "./logs"

[monitoring]
prometheus_enabled = true
prometheus_port = 8085

[raft]
general_raft_timeout_duration_in_ms = 100

[raft.commit_handler]
batch_size = 5000

[raft.replication]
rpc_append_entries_in_batch_threshold = 5000

[raft.persistence]
strategy = "MemFirst"
flush_policy = { Batch = { threshold = 1000, interval_ms = 100 } }


[retry.join_cluster]
max_retries = 3      # Maximum number of retries (recommended: 3)
timeout_ms = 500     # Single request timeout (recommended: 500-1000ms)
base_delay_ms = 3000 # Initial backoff delay (recommended: 3000ms)
max_delay_ms = 60000 # Maximum backoff delay (recommended: <=1m)

[raft.snapshot]
enable = true

[network.control]
concurrency_limit = 8192                #// Moderate concurrency
max_concurrent_streams = 8192           #// Stream limit for control operations
tcp_keepalive_in_secs = 3600            #// 5 minute TCP keepalive
http2_keep_alive_interval_in_secs = 300 #// Frequent pings
http2_keep_alive_timeout_in_secs = 20   #// Short timeout
max_frame_size = 16_777_215
connection_window_size = 2_097_152      #// 2MB connection window


[network.data]
connect_timeout_in_ms = 20              #// Balance speed and reliability
request_timeout_in_ms = 200             #// Accommodate log batches
concurrency_limit = 8192                #// High concurrency for parallel logs
max_concurrent_streams = 500            #// More streams for pipelining
tcp_keepalive_in_secs = 3600            #// 10 minute TCP keepalive
http2_keep_alive_interval_in_secs = 300 #// Moderate ping interval
http2_keep_alive_timeout_in_secs = 30   #// Longer grace period
max_frame_size = 16_777_215
connection_window_size = 6_291_456      #// 6MB connection window
