[network]
tcp_nodelay = true
# // buffer_size is the buffer size for grpc, default is 64kb = 64 * 1024.
buffer_size = 65536

[network.control]
connect_timeout_in_ms = 20             #// Fast failure for leader elections
request_timeout_in_ms = 100            #// Strict heartbeat timing
concurrency_limit = 1024               #// Moderate concurrency
max_concurrent_streams = 100           #// Stream limit for control operations
tcp_keepalive_in_secs = 300            #// 5 minute TCP keepalive
http2_keep_alive_interval_in_secs = 30 #// Frequent pings
http2_keep_alive_timeout_in_secs = 5   #// Short timeout
max_frame_size = 16_777_215
connection_window_size = 1_048_576     #// 1MB connection window
stream_window_size = 262_144           #// 256KB stream window
adaptive_window = false                #// Predictable behavior

[network.data]
connect_timeout_in_ms = 50              #// Balance speed and reliability
request_timeout_in_ms = 500             #// Accommodate log batches
concurrency_limit = 8192                #// High concurrency for parallel logs
max_concurrent_streams = 500            #// More streams for pipelining
tcp_keepalive_in_secs = 600             #// 10 minute TCP keepalive
http2_keep_alive_interval_in_secs = 120 #// Moderate ping interval
http2_keep_alive_timeout_in_secs = 30   #// Longer grace period
max_frame_size = 16_777_215
connection_window_size = 6_291_456      #// 6MB connection window
stream_window_size = 1_048_576          #// 1MB stream window
adaptive_window = true                  #// Optimize for varying loads

[network.bulk]
connect_timeout_in_ms = 500000          #// Allow for slow bulk connections
request_timeout_in_ms = 5000000         #// Disable request timeout
concurrency_limit = 4                   #// Limit parallel bulk transfers
max_concurrent_streams = 2              #// Minimal stream concurrency
tcp_keepalive_in_secs = 3600            #// Long-lived connections
http2_keep_alive_interval_in_secs = 600 #// 10 minute pings
http2_keep_alive_timeout_in_secs = 60   #// 1 minute timeout
max_frame_size = 16_777_215             #// Max allowed frame size
connection_window_size = 67_108_864     #// 64MB connection window
stream_window_size = 16_777_216         #// 16MB stream window
adaptive_window = false                 #// Stable throughput
