

[retry.append_entries]
max_retries = 1     # Maximum number of retries (recommended: 3-5)
timeout_ms = 100    # Single request timeout (recommended: 100-200ms)
base_delay_ms = 50  # Initial backoff delay (recommended: 50-100ms)
max_delay_ms = 1000 # Maximum backoff delay (recommended: <=1s)

[retry.election]
max_retries = 3     # Need higher fault tolerance
timeout_ms = 100    # Appropriately relax the timeout
base_delay_ms = 50  # Avoid being too aggressive
max_delay_ms = 5000 # Elections cannot wait indefinitely

[retry.membership]
# when there is a cluster membership changes, the max time to retry the sync.
# cluster membership sync can not failed. otherwise, server will panic!
# try for 10+ min = 120 * 500
max_retries = 120    # 10-minute fault tolerance (120*500ms=60s)
timeout_ms = 500     # Wait for the cluster to stabilize
base_delay_ms = 3000 # Member changes need to be more relaxed
max_delay_ms = 60000 # Upper limit 1 minute

[retry.healthcheck]
max_retries = 10000  # Nearly infinite retries
timeout_ms = 100     # Fast failure
base_delay_ms = 1000 # 1 second interval check
max_delay_ms = 10000 # Maximum 10 second interval

[retry.auto_discovery]
max_retries = 3     # Maximum number of retries (recommended: 3)
timeout_ms = 100    # Single request timeout (recommended: 100-200ms)
base_delay_ms = 50  # Initial backoff delay (recommended: 50-100ms)
max_delay_ms = 1000 # Maximum backoff delay (recommended: <=1s)


[retry.join_cluster]
max_retries = 3      # Maximum number of retries (recommended: 3)
timeout_ms = 500     # Single request timeout (recommended: 500-1000ms)
base_delay_ms = 3000 # Initial backoff delay (recommended: 3000ms)
max_delay_ms = 60000 # Maximum backoff delay (recommended: <=1m)


[retry.install_snapshot]
max_retries = 3     # Maximum number of retries (recommended: 3)
timeout_ms = 500    # Single request timeout (recommended: 500-1000ms)
base_delay_ms = 50  # Initial backoff delay (recommended: 50ms)
max_delay_ms = 2000 # Maximum backoff delay (recommended: <=2s)


[retry.purge_log]
max_retries = 1     # Maximum number of retries (recommended: 3-5)
timeout_ms = 100    # Single request timeout (recommended: 100-200ms)
base_delay_ms = 50  # Initial backoff delay (recommended: 50-100ms)
max_delay_ms = 1000 # Maximum backoff delay (recommended: <=1s)

[retry.internal_quorum]
max_retries = 3     # Maximum number of retries (recommended: must >=3)
timeout_ms = 100    # Single request timeout (recommended: 100-200ms)
base_delay_ms = 50  # Initial backoff delay (recommended: 50-100ms)
max_delay_ms = 1000 # Maximum backoff delay (recommended: <=1s)
