services:
  node1: &node-base
    image: demo:1.3
    cap_add:
      - NET_ADMIN # Add the NET_ADMIN capability
    environment:
      ID: 1
      PROMETHEUS_PORT: 8081
      LISTEN_PORT: 9081
      LOG_LEVEL: debug
      CONFIG_PATH: config/n1
      LOG_DIR: ./logs/1
      METRICS_PORT: 8081
      PEERS: '[{"id": 2,"name":"n2", "ip":"192.168.0.12", "port":9082, "role": 1}, {"id": 3,"name":"n3", "ip":"192.168.0.13", "port":9083, "role": 1}]'
    networks:
      mynetwork:
        ipv4_address: 192.168.0.11
    ports:
      - "2021:22"
      - "9081:9081"
    volumes:
      - ${SSH_KEYS_PATH:-./jepsen/sshkeys}:/root/.ssh
      - ${CONFIG_PATH:-./config}:/app/config
      - ${LOGS_PATH:-./output/logs}:/app/logs
      - ${DB_PATH:-./output/db}:/app/db
      # - ${SNAPSHOTS_PATH:-./output/snapshots}:/app/snapshots

  node2:
    <<: *node-base
    environment:
      ID: 2
      PROMETHEUS_PORT: 8082
      LISTEN_PORT: 9082
      LOG_LEVEL: debug
      CONFIG_PATH: config/n2
      LOG_DIR: ./logs/2
      METRICS_PORT: 8082
      PEERS: '[{"id": 1,"name":"n1", "ip":"192.168.0.11", "port":9081, "role": 1}, {"id": 3,"name":"n3", "ip":"192.168.0.13", "port":9083, "role": 1}]'
    networks:
      mynetwork:
        ipv4_address: 192.168.0.12
    ports:
      - "2022:22"
      - "9082:9082"

  node3:
    <<: *node-base
    environment:
      ID: 3
      PROMETHEUS_PORT: 8083
      LISTEN_PORT: 9083
      LOG_LEVEL: debug
      CONFIG_PATH: config/n3
      LOG_DIR: ./logs/3
      METRICS_PORT: 8083
      PEERS: '[{"id": 2,"name":"n2", "ip":"192.168.0.12", "port":9082, "role": 1}, {"id": 1,"name":"n1", "ip":"192.168.0.11", "port":9081, "role": 1}]'
    networks:
      mynetwork:
        ipv4_address: 192.168.0.13
    ports:
      - "2023:22"
      - "9083:9083"

  jepsen:
    image: jepsen:1.0
    cap_add:
      - NET_ADMIN # Add the NET_ADMIN capability
    environment:
      N1: 192.168.0.11
      N2: 192.168.0.12
      N3: 192.168.0.13
      ENDPOINTS: http://node3:9083/,http://node2:9082/,http://node1:9081/
      TIME_LIMIT: 1
    networks:
      mynetwork:
        ipv4_address: 192.168.0.14
    ports:
      - "2024:22"
    volumes:
      - ${JEP_STORE_PATH:-./jepsen/store}:/app/store
    depends_on:
      - node1
      - node2
      - node3

volumes:
  prometheus_data:
  grafana_data:

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
