{
 "title": "Master",
 "tags": [ "autometrics" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "function",
    "label": "Show Function(s)",
    "query": {
     "query": "label_values({__name__=~\"function_calls(_count)?(_total)?\"}, function)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Append Timeout Setting",
   "type": "logs",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"dengine\"}\n  | decolorize      \n  |~ \"New Append Timeout Metric.\"      \n  |~ \"INFO\"      \n  | pattern `<timestamp> <level> <component>: <message>. timeout: <timeout>. peer_id: <peer_id>.` \n  | line_format \"peer_{{ .peer_id }} - {{ .timeout }} \""
    }
   ]
  },
  {
   "title": "Append Amount Setting",
   "type": "logs",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"dengine\"}\n |~ \"INFO\" \n |~ \"New Append Amount Metric\" \n | pattern `<timestamp> <level> <component>. amount: <amount>. peer_id: <peer_id>.` \n | line_format \"peer_{{ .peer_id }}: {{ .amount }} \""
    }
   ]
  },
  {
   "title": "ElectionTimeout",
   "type": "logs",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"dengine\"}\n |~ \"INFO\" \n |~ \"New Election Timeout\" \n | pattern `<timestamp> <level> <component> New Election Timeout: <amount>. peer_id: <peer_id>.` \n | line_format \"peer_{{ .peer_id }}: {{ .amount }} \""
    }
   ]
  },
  {
   "title": "Failed Commit Msgs",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "targets": [
    { "expr": "sum(failed_commit_messages)\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_size",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(message_size_sum) / count(message_size_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "committed_log",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(committed_log) by (id)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message latency",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "sum(message_commit_latency_metric_sum) / count(message_commit_latency_metric_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fun Duration(ms)",
   "type": "bargauge",
   "gridPos": { "h": 68, "w": 13, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg by (function) (\n  rate(function_calls_duration_seconds_sum{function=~\"$function\"}[1m])\n  /\n  clamp_min(rate(function_calls_duration_seconds_count{function=~\"$function\"}[1m]), 0.001)\n)* 1000 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fun Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(function_calls_duration_seconds_sum{function=~\"$function\"}[5m])) by (function)\n/\nsum(rate(function_calls_duration_seconds_count{function=~\"$function\"}[5m])) by (function)\n* 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "slow_res_duration_metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(slow_res_duration_metric_bucket[5m])) by (le, peer_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "unsynced_msg_metric",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 36 },
   "targets": [
    { "expr": "unsynced_msg_metric", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster Errors",
   "type": "logs",
   "gridPos": { "h": 29, "w": 11, "x": 13, "y": 44 },
   "targets": [
    {
     "expr": "{job=\"dengine\"}\n |~ \"ERROR\" \n "
    }
   ]
  }
 ]
}