// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: proto/client/client_api.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftClientService_HandleClientWrite_FullMethodName = "/d_engine.client.RaftClientService/HandleClientWrite"
	RaftClientService_HandleClientRead_FullMethodName  = "/d_engine.client.RaftClientService/HandleClientRead"
	RaftClientService_Watch_FullMethodName             = "/d_engine.client.RaftClientService/Watch"
)

// RaftClientServiceClient is the client API for RaftClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftClientServiceClient interface {
	HandleClientWrite(ctx context.Context, in *ClientWriteRequest, opts ...grpc.CallOption) (*ClientResponse, error)
	HandleClientRead(ctx context.Context, in *ClientReadRequest, opts ...grpc.CallOption) (*ClientResponse, error)
	// Watch for changes on a specific key
	//
	// Returns a stream of WatchResponse events whenever the watched key changes.
	// The stream remains open until the client cancels or disconnects.
	//
	// Performance characteristics:
	// - Event notification latency: typically < 100μs
	// - Minimal overhead on write path (< 0.01% with 100+ watchers)
	//
	// Error handling:
	// - If the internal event buffer is full, events may be dropped
	// - Clients should use Read API to re-sync if they detect gaps
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
}

type raftClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftClientServiceClient(cc grpc.ClientConnInterface) RaftClientServiceClient {
	return &raftClientServiceClient{cc}
}

func (c *raftClientServiceClient) HandleClientWrite(ctx context.Context, in *ClientWriteRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, RaftClientService_HandleClientWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClientServiceClient) HandleClientRead(ctx context.Context, in *ClientReadRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, RaftClientService_HandleClientRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClientServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RaftClientService_ServiceDesc.Streams[0], RaftClientService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftClientService_WatchClient = grpc.ServerStreamingClient[WatchResponse]

// RaftClientServiceServer is the server API for RaftClientService service.
// All implementations must embed UnimplementedRaftClientServiceServer
// for forward compatibility.
type RaftClientServiceServer interface {
	HandleClientWrite(context.Context, *ClientWriteRequest) (*ClientResponse, error)
	HandleClientRead(context.Context, *ClientReadRequest) (*ClientResponse, error)
	// Watch for changes on a specific key
	//
	// Returns a stream of WatchResponse events whenever the watched key changes.
	// The stream remains open until the client cancels or disconnects.
	//
	// Performance characteristics:
	// - Event notification latency: typically < 100μs
	// - Minimal overhead on write path (< 0.01% with 100+ watchers)
	//
	// Error handling:
	// - If the internal event buffer is full, events may be dropped
	// - Clients should use Read API to re-sync if they detect gaps
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	mustEmbedUnimplementedRaftClientServiceServer()
}

// UnimplementedRaftClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftClientServiceServer struct{}

func (UnimplementedRaftClientServiceServer) HandleClientWrite(context.Context, *ClientWriteRequest) (*ClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleClientWrite not implemented")
}
func (UnimplementedRaftClientServiceServer) HandleClientRead(context.Context, *ClientReadRequest) (*ClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleClientRead not implemented")
}
func (UnimplementedRaftClientServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedRaftClientServiceServer) mustEmbedUnimplementedRaftClientServiceServer() {}
func (UnimplementedRaftClientServiceServer) testEmbeddedByValue()                           {}

// UnsafeRaftClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftClientServiceServer will
// result in compilation errors.
type UnsafeRaftClientServiceServer interface {
	mustEmbedUnimplementedRaftClientServiceServer()
}

func RegisterRaftClientServiceServer(s grpc.ServiceRegistrar, srv RaftClientServiceServer) {
	// If the following call panics, it indicates UnimplementedRaftClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftClientService_ServiceDesc, srv)
}

func _RaftClientService_HandleClientWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftClientServiceServer).HandleClientWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftClientService_HandleClientWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftClientServiceServer).HandleClientWrite(ctx, req.(*ClientWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftClientService_HandleClientRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftClientServiceServer).HandleClientRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftClientService_HandleClientRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftClientServiceServer).HandleClientRead(ctx, req.(*ClientReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftClientService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RaftClientServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftClientService_WatchServer = grpc.ServerStreamingServer[WatchResponse]

// RaftClientService_ServiceDesc is the grpc.ServiceDesc for RaftClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "d_engine.client.RaftClientService",
	HandlerType: (*RaftClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleClientWrite",
			Handler:    _RaftClientService_HandleClientWrite_Handler,
		},
		{
			MethodName: "HandleClientRead",
			Handler:    _RaftClientService_HandleClientRead_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _RaftClientService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/client/client_api.proto",
}
