name: Rust

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt # Ensure rustfmt is installed

      - name: Check Formatting
        run: cargo fmt --all -- --check # Verify code formatting compliance

  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Install Protobuf compiler
        run: sudo apt-get install protobuf-compiler

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run tests with Tarpaulin
        run: cargo tarpaulin --all-features --out Xml --ciserver github

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: cobertura.xml
          verbose: true
